# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-13 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='age',
            new_name='user_type',
        ),
    ]
