# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-17 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_auto_20240116_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='private_key',
            new_name='_p_key',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='public_key',
            new_name='p_key',
        ),
    ]
